apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          command: ["sleep"]
          args: ["infinity"]
          image: ourtiii/docker_client_k8s:latest
          ports:
            - containerPort: 5050
