apiVersion: apps/v1
kind: Deployment
metadata:
  name: monserveur
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monserveur
  template:
    metadata:
      labels:
        app: monserveur
    spec:
      containers:
        - name: monserveur
          image: ourtiii/docker_server:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: monserveur
spec:
  type: NodePort
  selector:
    app: monserveur
  ports:
    - port: 80
      targetPort: 5000
